### ISSUE TITLE
Commits/edits from different team members

### ISSUE THREAD

**Issue by hothost87** [CPVazquez/3354-MEK-TEK#3]
Make sure the scope is reviewed/confirmed by all team members, via interactions on git.

**Comment by thedhruvn** [comment]
Should I re-open a pull request and wait for them to approve it before merging?

**Comment by hothost87** [comment]
You can do that. But I am also expecting >1 team members contributing to the creation/evolution of project contents. So I expect activities from ALL, according to the project assignment 0 instruction.

**Comment by thedhruvn** [comment]
Got it. Maybe I'll let them edit and re-open the pull-request then!

**Comment by hothost87** [comment]
That's fine. Thanks.
