### ISSUE TITLE
Comment/Remove Deprecated Code the following Documents (check off the tasks inside this as you go):

### ISSUE THREAD

**Issue by thedhruvn** [CPVazquez/3354-MEK-TEK#48]
- [x] MainActivity (needs comments, needs to be cleansed)
- [x] DatabaseHandler (needs comments after getProcessTree)
- [x] Search
- [x] Dimension
- [x] NetworkGraph
- [x] Point2D
- [x] RandomLocationTransformer
- [x] Vertex
- [x] ArcUtils
- [x] Layout FOLDER: Layout
- [x] FRLayout
- [x] AbstractLayout

**Comment by Kaeladin** [comment]
Done~
