### ISSUE TITLE
Need to link specific commits to examples in refactoring and implementing design patterns

### ISSUE THREAD

**Issue by thedhruvn** [CPVazquez/3354-MEK-TEK#49]
I think I have one such pattern on the diff link on the slides

I think I committed recently and I...edited something? not sure, I'll check.

**Comment by thedhruvn** [comment]
Oh, these need to be linked to the P3_DOC file, for our submission, btw. I am making the .md file now.

**Comment by Kaeladin** [comment]
No need to include link to commits
