### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by hothost87** [CPVazquez/3354-MEK-TEK#9]
Saw the database design. Progress on GUI?

**Comment by ChandranshuRao14** [comment]
We started the GUI on the AnshuAndroid branch and wrote all the classes from our class diagram which are all located in the PolycraftApp/app/src/main folder. We are currently working on implementing the draw and search functionality in the ActivityMain.java, however, those changes have not been pushed yet and we expect to push those changes later today.

**Comment by hothost87** [comment]
Great! Thanks.
